"""READ-ONLY backfill: assign evidence_type to legacy null intent_signals.

Runs the same two-stage classifier (regex → strict LLM) used by the
gateway's _autotag_evidence_type on every fulfillment_request row that
has any null evidence_type in icp_details.intent_signals.

Output: a single .sql file at /tmp/backfill_evidence_type.sql containing
UPDATE statements you can review and run in the Supabase SQL editor.

Per the user's read-only feedback rule, this script does NOT call any
write operation against Supabase.  Per the iterate-per-issue rule, it
processes one request at a time and prints progress so you can stop
early if something looks off.
"""
import os
import sys
import json
import asyncio
import collections
from typing import Any, Dict, List, Optional

sys.path.insert(0, "/Users/tasnimul/Desktop/leadpoet")

from dotenv import load_dotenv

load_dotenv("/Users/tasnimul/Desktop/leadpoet/.env")

from supabase import create_client  # noqa: E402
from qualification.scoring.intent_precheck import (  # noqa: E402
    _classify_target_type,
    llm_classify_evidence_type,
)


SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
OUTPUT_SQL = "/tmp/backfill_evidence_type.sql"
# Restrict to still-live chains so we don't churn ancient rows.
ACTIVE_STATUSES = {"open", "in_progress", "queued", "commit_open",
                   "commit_closed", "scoring", "partially_fulfilled"}


def sql_quote(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


async def main() -> None:
    if not SUPABASE_URL or not SUPABASE_KEY:
        print("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY")
        sys.exit(1)
    sb = create_client(SUPABASE_URL, SUPABASE_KEY)

    rows = (
        sb.table("fulfillment_requests")
          .select("request_id, icp_details, status, created_at")
          .order("created_at", desc=True)
          .limit(2000)
          .execute()
          .data
        or []
    )
    print(f"Inspecting {len(rows)} most recent fulfillment_requests rows...")

    classifier_dist = collections.Counter()
    sql_statements: List[str] = []
    updated_rows = 0
    skipped_inactive = 0
    skipped_no_nulls = 0

    for row in rows:
        rid = row["request_id"]
        status = row.get("status") or ""
        if status not in ACTIVE_STATUSES:
            skipped_inactive += 1
            continue
        icp = row.get("icp_details") or {}
        signals = icp.get("intent_signals") or []
        if not isinstance(signals, list):
            continue
        # Identify nulls.
        null_indices = [
            i for i, s in enumerate(signals)
            if isinstance(s, dict) and not s.get("evidence_type")
        ]
        if not null_indices:
            skipped_no_nulls += 1
            continue

        # Classify each null one at a time.
        changed = False
        for i in null_indices:
            text = signals[i].get("text") or ""
            cls = _classify_target_type(text)
            stage = "regex"
            if cls is None:
                cls = await llm_classify_evidence_type(text)
                stage = "llm" if cls else "failed"
            if cls is None:
                print(
                    f"  [{rid[:8]}.. sig#{i}] NO CLASSIFICATION: "
                    f"{text[:80]!r}"
                )
                continue
            signals[i]["evidence_type"] = cls
            classifier_dist[(stage, cls)] += 1
            changed = True
            print(f"  [{rid[:8]}.. sig#{i}] {stage}={cls}: {text[:60]!r}")

        if changed:
            updated_rows += 1
            new_icp = dict(icp)
            new_icp["intent_signals"] = signals
            payload = json.dumps(new_icp)
            sql_statements.append(
                f"UPDATE public.fulfillment_requests "
                f"SET icp_details = {sql_quote(payload)}::jsonb "
                f"WHERE request_id = {sql_quote(rid)};"
            )

    # Write SQL file
    with open(OUTPUT_SQL, "w") as f:
        f.write("-- READ-REVIEW-RUN backfill for evidence_type nulls.\n")
        f.write(f"-- Generated by backfill_evidence_type.py on "
                f"active requests only ({sorted(ACTIVE_STATUSES)}).\n")
        f.write("-- Run as a single transaction inside the Supabase SQL editor.\n\n")
        f.write("BEGIN;\n")
        f.writelines(s + "\n" for s in sql_statements)
        f.write("COMMIT;\n")

    print()
    print(f"=== Summary ===")
    print(f"  Rows updated:        {updated_rows}")
    print(f"  Skipped (inactive):  {skipped_inactive}")
    print(f"  Skipped (no nulls):  {skipped_no_nulls}")
    print(f"  Per-stage distribution:")
    for (stage, cls), n in classifier_dist.most_common():
        print(f"    {stage:>6s}  {cls:>25s}  {n}")
    print(f"\nSQL written to: {OUTPUT_SQL}")
    print(f"  Review with:  less {OUTPUT_SQL}")
    print(f"  Run via:      Supabase SQL editor (paste contents)")


if __name__ == "__main__":
    asyncio.run(main())
