"""Open deterministic verifier surface for Leadpoet Research Lab.

This package intentionally depends only on the Python standard library. It is
the Phase 0 extraction target for checks and arithmetic that validators should
be able to rerun without sealed judge code, gateway services, or network I/O.
"""

from .aggregation import (
    DEFAULT_INTENT_SIGNAL_DECAY_25_PCT_MONTHS,
    DEFAULT_INTENT_SIGNAL_DECAY_50_PCT_MONTHS,
    MAX_COMPANY_ICP_FIT_SCORE,
    MAX_COMPANY_INTENT_SIGNAL_SCORE,
    MAX_COMPANY_TOTAL_SCORE,
    NO_DATE_DECAY_MULTIPLIER,
    SOURCE_TYPE_MULTIPLIERS,
    aggregate_set_score,
    apply_signal_time_decay,
    calculate_age_months,
    calculate_time_decay_multiplier,
    company_final_score,
    per_icp_normalized_score,
    u16_weights_from_scores,
)
from .attestation import (
    is_pcr0_allowed,
    load_pcr0_allowlist,
    validate_attestation_response_shape,
)
from .crowning import (
    DEFAULT_DELTA_MIN_FLOOR,
    DEFAULT_OC_SIMULATION_ITERATIONS,
    DEFAULT_OC_SIMULATION_SEED,
    DEFAULT_REENTRY_CAP_PER_7_DAYS,
    DEFAULT_REQUIRED_TEMPORAL_BUFFER_DAYS,
    DEFAULT_TEMPORAL_BUFFER_MAX_SAME_DAY,
    GROUP_SEQUENTIAL_T_BOUNDARY_BY_N,
    MAX_PROBATION_LOOKS,
    MIN_PROBATION_LOOKS,
    PROBATION_LOOKS,
    STUDENT_T_ONE_SIDED_95_BY_N,
    attacker_expected_value,
    boundary_for_look,
    ceiling_utilization,
    check_grant_curve_shape,
    compound_reentry_probability,
    continuity_floor,
    derive_delta_min,
    evaluate_crowning,
    lower_confidence_bound,
    operating_characteristic_curve,
    paired_deltas,
    paired_stats,
    probability_crosses_boundary,
    simulate_sequential_crown_probability,
)
from .l0 import (
    Finding,
    L0Result,
    check_date_precision,
    compute_snippet_overlap,
    run_l0_checks,
)
from .static_checks import StaticCheckResult, run_static_gaming_checks

__all__ = [
    "Finding",
    "L0Result",
    "StaticCheckResult",
    "DEFAULT_INTENT_SIGNAL_DECAY_25_PCT_MONTHS",
    "DEFAULT_INTENT_SIGNAL_DECAY_50_PCT_MONTHS",
    "DEFAULT_OC_SIMULATION_ITERATIONS",
    "DEFAULT_OC_SIMULATION_SEED",
    "MAX_COMPANY_ICP_FIT_SCORE",
    "MAX_COMPANY_INTENT_SIGNAL_SCORE",
    "MAX_COMPANY_TOTAL_SCORE",
    "MAX_PROBATION_LOOKS",
    "MIN_PROBATION_LOOKS",
    "NO_DATE_DECAY_MULTIPLIER",
    "PROBATION_LOOKS",
    "SOURCE_TYPE_MULTIPLIERS",
    "STUDENT_T_ONE_SIDED_95_BY_N",
    "aggregate_set_score",
    "apply_signal_time_decay",
    "attacker_expected_value",
    "boundary_for_look",
    "calculate_age_months",
    "calculate_time_decay_multiplier",
    "ceiling_utilization",
    "check_date_precision",
    "check_grant_curve_shape",
    "company_final_score",
    "compute_snippet_overlap",
    "compound_reentry_probability",
    "continuity_floor",
    "derive_delta_min",
    "evaluate_crowning",
    "is_pcr0_allowed",
    "load_pcr0_allowlist",
    "lower_confidence_bound",
    "operating_characteristic_curve",
    "paired_deltas",
    "paired_stats",
    "per_icp_normalized_score",
    "probability_crosses_boundary",
    "run_l0_checks",
    "run_static_gaming_checks",
    "simulate_sequential_crown_probability",
    "u16_weights_from_scores",
    "validate_attestation_response_shape",
    "DEFAULT_DELTA_MIN_FLOOR",
    "DEFAULT_REENTRY_CAP_PER_7_DAYS",
    "DEFAULT_REQUIRED_TEMPORAL_BUFFER_DAYS",
    "DEFAULT_TEMPORAL_BUFFER_MAX_SAME_DAY",
    "GROUP_SEQUENTIAL_T_BOUNDARY_BY_N",
]
